#' Quickly Plot CanVec Data
#' 
#' Quickly plot basic CanVec data (lakes, rivers, contours, buildings, and roads) with options
#' to change the plotting style of each. If data does not exist in the cache
#' it will be downloaded.
#' 
#' @param ntsid One or more NTS References as generated by \code{nts()}
#' @param bbox A bounding box describing the desired extent. If no \code{ntsid} is
#' provided, nts(bbox=bbox) will be invoked to find the appropriate NTS Reference(s)
#' @param waterbody TRUE if waterbody (lakes) layer should be drawn
#' @param river TRUE if river layer should be drawn
#' @param contour TRUE if contour layer should be drawn
#' @param building TRUE if building layer should be drawn
#' @param road TRUE if road layer should be drawn
#' @param waterbody.col Colour to fill waterbody polygons
#' @param waterbody.border Colour to outline waterbody polygons
#' @param contour.col Colour to draw contour lines
#' @param contour.lwd Width of contour lines
#' @param river.col Colour to draw rivers
#' @param river.lwd Width to draw rivers
#' @param road.col Colour to draw roads
#' @param road.lwd Width to draw roads
#' @param building.pch Symbol to draw for buildings
#' @param building.col Colour to draw buildings
#' @param plotdata TRUE if plot() should be invoked to draw data. FALSE if just loading data
#' is desired.
#' @param cachedir Pass a specific cache directory in which files have been extracted.
#'                  Default value is that returned by \code{canvec.cachedir()}
#' @param data A list object that contains the loaded Spatial* data to be plotted.
#' This should always be an object that was returned by \code{canvec.qplot()}
#' @param atscale One of \code{nts.SCALE50K} or \code{nts.SCALE250K}
#' @param ... A list of graphical parameters passed to the inital call to \code{plot()}.
#' Note that xlim and ylim will generate an error - instead use the bbox argument.
#' @return A list object that contains the Spatial* data that was plotted
#' 
#' @examples
#' plotdata <- canvec.qplot(nts("21h1"), contour=TRUE, building=TRUE, road=TRUE)
#' plotdata <- canvec.qplot(bbox=makebbox(45.1, -64.35, 45.05, -64.4), 
#'                         contour=TRUE, building=TRUE, road=TRUE,
#'                         data=plotdata)
#' 
#' @export
canvec.qplot <- function(ntsid=NULL, bbox=NULL, waterbody=TRUE, river=TRUE, contour=FALSE, building=FALSE, road=FALSE,
                         waterbody.col="lightblue", waterbody.border="lightblue", contour.col="brown",
                         contour.lwd=0.2, river.col="lightblue", river.lwd=1, road.col="black", road.lwd=0.5,
                         building.pch=".", building.col="black", plotdata=TRUE, cachedir=NULL, data=NULL, atscale=nts.SCALE50K, ...) {
  
  
  if(!is.null(bbox)) {
    if(is.null(ntsid)) {
      ntsid <- nts(bbox=bbox, atscale = atscale)
    }
    xlim <- bbox[1,]
    ylim <- bbox[2,]
  } else if(is.null(ntsid)) {
    stop("No arguments specified for data to plot")
  }
  
  if(is.null(cachedir)) {
    cachedir <- canvec.cachedir()
  }
  
  if(class(ntsid) != "list") {
    ntsid <- list(ntsid)
  }
  
  if(is.null(data)) {
    #download
    canvec.download(ntsid, cachedir=cachedir)
    #load data
    data <- list()
  }
  
  #does not take into account changed ntsids
  if(waterbody && is.null(data$waterbody))
    data$waterbody <- canvec.load(ntsid, "waterbody", cachedir=cachedir)
  if(building && is.null(data$building))
    data$building <- canvec.load(ntsid, "building", cachedir=cachedir)
  if(river && is.null(data$river))
    data$river <- canvec.load(ntsid, "river", cachedir=cachedir)
  if(road && is.null(data$road))
    data$road <- canvec.load(ntsid, "road", cachedir=cachedir)
  if(contour && is.null(data$contour))
    data$contour <- canvec.load(ntsid, "contour", cachedir=cachedir)
  
  if(plotdata) {
    #plot corners of mapsheet extents 
    if(class(ntsid)=="list") {
      if(length(ntsid)==0) stop("Cannot plot background for zero mapsheets")
      bbox1 <- nts.bbox(ntsid[[1]])
      for(singleid in ntsid) {
        bbox2 <- nts.bbox(singleid)
        bbox1 <- matrix(c(min(bbox1[1,1], bbox2[1,1]), min(bbox1[2,1], bbox2[2,1]),
                          max(bbox1[1,2], bbox2[1,2]), max(bbox1[2,2], bbox2[2,2])), ncol=2, byrow=FALSE)
      }
    } else {
      bbox1 = nts.bbox(ntsid)
    }
    coords <- coordinates(t(bbox1))
    spoints = SpatialPoints(coords, proj4string = CRS("+proj=longlat +ellps=GRS80 +no_defs"))
    
    #THIS DOES NOT WORK AS PREDICTED, if xlim or ylim are passed this generates an error
    if(is.null(bbox)) {
      xlim <- bbox1[1,]
      ylim <- bbox1[2,]
    }
    plot(spoints, pch=".", xlim=xlim, ylim=ylim, ...)
    
    if(waterbody)
      for(layer in data$waterbody) plot(layer, add=TRUE, col=waterbody.col, border=waterbody.border)
    if(contour)
      for(layer in data$contour) plot(layer, add=TRUE, col=contour.col, lwd=contour.lwd)
    if(river)
      for(layer in data$river) plot(layer, add=TRUE, col=river.col, lwd=river.lwd)
    if(building)
      for(layer in data$building) plot(layer, add=TRUE, pch=building.pch, col=building.col)
    if(road)
      for(layer in data$road) plot(layer, add=TRUE, lwd=road.lwd, col=road.col)
  }
  
  invisible(data)
}